// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFeFwxrVML9KRFaf21-L8J98HmnHC513k',
    appId: '1:703266485712:web:7b0f6c6a59e47490ddf5d5',
    messagingSenderId: '703266485712',
    projectId: 'evently-58f25',
    authDomain: 'evently-58f25.firebaseapp.com',
    storageBucket: 'evently-58f25.firebasestorage.app',
    measurementId: 'G-0KR2WHG258',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx4Hjw4X3Aj12w9onMjxm4kARhVNgIUxM',
    appId: '1:703266485712:android:7c2a409ab2b6b278ddf5d5',
    messagingSenderId: '703266485712',
    projectId: 'evently-58f25',
    storageBucket: 'evently-58f25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc9KqnxayyuqlD1qbBXke1UjQn0aDblDo',
    appId: '1:703266485712:ios:d273c99b66d96625ddf5d5',
    messagingSenderId: '703266485712',
    projectId: 'evently-58f25',
    storageBucket: 'evently-58f25.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc9KqnxayyuqlD1qbBXke1UjQn0aDblDo',
    appId: '1:703266485712:ios:d273c99b66d96625ddf5d5',
    messagingSenderId: '703266485712',
    projectId: 'evently-58f25',
    storageBucket: 'evently-58f25.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFeFwxrVML9KRFaf21-L8J98HmnHC513k',
    appId: '1:703266485712:web:1d75c7d4d41b77f5ddf5d5',
    messagingSenderId: '703266485712',
    projectId: 'evently-58f25',
    authDomain: 'evently-58f25.firebaseapp.com',
    storageBucket: 'evently-58f25.firebasestorage.app',
    measurementId: 'G-PCTKJB8Z72',
  );
}
